title: "Rijkshuisstijl interpretatie"
body:
  - type: input
    id: component_naam
    attributes:
      label: "Naam van het onderdeel"
      placeholder: "Bijv. Button"

  - type: markdown
    attributes:
      value: |
        # {{component_naam}} – Rijkshuisstijl keuzes  
        _Laatste update: {{today}}_  

        ## Keuzes en overwegingen

        <!---
        Noteer hier per onderwerp welke ontwerpkeuze is gemaakt, waarom deze keuze is gemaakt, én op basis van welke informatie of bron (zoals onderzoek, huisstijl of WCAG-richtlijnen).
        Gebruik de onderstaande structuur en voeg onderwerpen toe die relevant zijn, zoals kleurgebruik, focusstijl of afgeronde hoeken. Combineer de keuze, de reden en eventuele onderbouwing in één korte alinea per punt. 
        -->
  - type: textarea
    id: keuzes_overwegingen
    attributes:
      label: "Keuzes en overwegingen"
      placeholder: |
        Voorbeeld:
        **Kleurgebruik:** Er is gekozen voor donkerblauw (#003082) omdat dit de primaire kleur uit de Rijkshuisstijl is en voldoende contrast biedt volgens WCAG AA.
