title: Rijkshuisstijl keuze
labels:
  - rijkshuisstijl
body:
  - type: input
    id: component_naam
    attributes:
      label: Naam van onderdeel
      description: Geef aan voor welk component of onderdeel deze keuzes gelden
      placeholder: Bijv. Button, Inputveld, etc.

  - type: textarea
    id: keuzes_en_overwegingen
    attributes:
      label: Keuzes en overwegingen
      description: Noteer hier ontwerpkeuzes, motivatie en onderbouwing (zoals WCAG, onderzoek, huisstijl).
      placeholder: |
        Voorbeeld:
        **Kleurgebruik:** Donkerblauw (#003082) voor primaire knoppen. Dit voldoet aan contrastvereisten (WCAG AA).

  - type: markdown
    attributes:
      value: |
        ---
        ## 📄 Voorvertoning

        Gebruik onderstaande preview als Markdown in documentatie of overdracht:

        ```markdown
        ## {{component_naam}} – Rijkshuisstijl keuzes
        Laatste update: {{date}}

        ### Keuzes en overwegingen

        {{keuzes_en_overwegingen}}
        ```
